-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-gjlw_namespace_text.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX gjlw_wiki_id;
ALTER TABLE globaljsonlinks_wiki
  ADD gjlw_namespace INT DEFAULT NULL;
ALTER TABLE globaljsonlinks_wiki
  ADD gjlw_namespace_text TEXT DEFAULT NULL;

CREATE UNIQUE INDEX gjlw_wiki_id_namespace ON globaljsonlinks_wiki (
  gjlw_wiki, gjlw_namespace, gjlw_namespace_text
);
