-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-gjlw_namespace_text.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX gjlw_wiki_id ON /*_*/globaljsonlinks_wiki;
ALTER TABLE /*_*/globaljsonlinks_wiki
  ADD gjlw_namespace INT DEFAULT NULL,
  ADD gjlw_namespace_text VARBINARY(255) DEFAULT NULL;

CREATE UNIQUE INDEX gjlw_wiki_id_namespace ON /*_*/globaljsonlinks_wiki (
    gjlw_wiki, gjlw_namespace, gjlw_namespace_text
  );
